import Loading from "@/components/loading/Loading";
import "./globals.css";
import QueryProvider from "./QueryProvider";

import { Inter } from 'next/font/google'
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

export const metadata = {
  title: "QR order client",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin']
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <Loading type={'link'} />
          {children}
          <ReactQueryDevtools initialIsOpen={false} />
        </QueryProvider>
      </body>
    </html>
  );
}
