import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Inter } from 'next/font/google'

export const metadata = {
  title: "QR order",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin']
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
